name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Node 18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:unit
      - run: npm run build
  e2e:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Node 18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: xvfb-run --auto-servernum -- npm run test:e2e
